# Config for GCP deployment
runtime: custom
env: flex
entrypoint: ./entrypoint.sh
resources:
  cpu: 2
  memory_gb: 4.0
  disk_size_gb: 32
network:
  session_affinity: true
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.8