# Config for GCP deployment
runtime: custom
env: flex
runtime_config:
  python_version: 3
resources:
  cpu: 2
  memory_gb: 4.0
  disk_size_gb: 32
network:
  session_affinity: true
readiness_check:
  app_start_timeout_sec: 180
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.8