# Config for GCP deployment
runtime: custom

env: flex

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

network:
  session_affinity: true

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10  # Disk size must be between 10GB and 10240GB
