name: emotts
channels:
  - conda-forge
  - pypi
  - pytorch
dependencies:
  - baumwelch
  - click
  - cpuonly
  - enum34
  - fastapi
  - gdown
  - git
  - inflect
  - kaldi
  - librosa
  - llvmlite
  - marshmallow
  - marshmallow-dataclass
  - matplotlib
  - montreal-forced-aligner=2.0.0b4
  - ngram
  - numpy
  - openblas
  - openfst
  - pip
  - pynini
  - pysoundfile
  - python=3.8
  - pytorch
  - pyyaml
  - scipy
  - sox
  - tensorboard
  - torchaudio
  - tqdm
  - types-pyyaml
  - unidecode
  - unzip
  - uvicorn
  - pip:
    - tgt