name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5

  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        checks: ['make flake8', 'make mypy', 'make test']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.7

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-check-${{ hashFiles('**/requirements**.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools
        python -m pip install -r requirements-dev.txt

    - name: Run checks
      id: run_checks
      run: ${{ matrix.checks }}
