from dataclasses import field, dataclass
from typing import List, Optional


@dataclass
class GaussianUpsampleConfig:

    eps: float = field(default=1e-20)
    max_len: int = field(default=1024)
    attention_dropout: float = field(default=0.1)
    positional_dropout: float = field(default=0.1)


@dataclass
class TacatronDurationConfig:

    lstm_layers: int = field(default=2)
    lstm_hidden: int = field(default=256)
    dropout: float = field(default=0.5)


@dataclass
class TacatronRangeConfig:

    lstm_layers: int = field(default=2)
    lstm_hidden: int = field(default=256)
    dropout: float = field(default=0.5)


@dataclass
class TacatronEncoderConfig:

    duration_config: TacatronDurationConfig
    range_config: TacatronRangeConfig
    n_convolutions: int = field(default=3)
    kernel_size: int = field(default=5)


@dataclass
class TacatronConfig:

    encoder_config: TacatronEncoderConfig
    positional_config = GaussianUpsampleConfig
    mask_padding: bool = field(default=True)
    fp16_run: bool = field(default=False)
    n_mel_channels: int = field(default=80)
    n_frames_per_step: int = field(default=513)
    n_phonems: int = field(default=4000)
    phonem_embedding_dim: int = field(default=512)
    n_speakers: int = field(default=4)
    speaker_embedding_dim: int = field(default=256)


@dataclass
class NetworkParams:
    cleaners: str = field(default="basic_cleaners")
    use_phonemes: bool = field(default=True)
    enable_eos: bool = field(default=False)
    use_lpc_features: bool = field(default=False)
    lpc_dump_data: str = field(default="/tasks/LPCNet_master/build/dump_data -test")
    to_cut_pauses: bool = field(default=True)
    normalize_features: bool = field(default=True)
    normalization_std: float = field(default=1.0)
    use_vad_trimming: bool = field(default=True)
    normalize_wav_by_energy: bool = field(default=True)
    vad_window_length: int = field(default=30)
    vad_moving_average_width: int = field(default=8)
    vad_max_silence_length: int = field(default=6)
    audio_norm_target_dBFS: int = field(default=-29)
    target_sampling_rate: int = field(default=22050)
    tacotron_num_gpus: int = field(default=1)
    wavenet_num_gpus: int = field(default=1)
    split_on_cpu: bool = field(default=True)
    num_mels: int = field(default=80)
    num_freq: int = field(default=513)
    rescale: bool = field(default=True)
    rescaling_max: float = field(default=0.999)
    clip_mels_length: bool = field(default=False)
    max_mel_frames: int = field(default=1500)
    use_lws: bool = field(default=False)
    silence_threshold: int = field(default=2)
    n_fft: int = field(default=1024)
    hop_size: int = field(default=256)
    win_size: int = field(default=1024)
    sample_rate: int = field(default=22050)
    frame_shift_ms: Optional[int] = field(default=None)
    trim_silence: bool = field(default=True)
    trim_fft_size: int = field(default=2048)
    trim_hop_size: int = field(default=512)
    trim_top_db: int = field(default=40)
    allow_clipping_in_normalization: bool = field(default=True)
    symmetric_mels: bool = field(default=True)
    max_abs_value: float = field(default=4.0)
    preemphasize: bool = field(default=True)
    preemphasis: float = field(default=0.97)
    min_level_db: int = field(default=-100)
    ref_level_db: int = field(default=20)
    fmin: int = field(default=55)
    fmax: int = field(default=7600)
    input_type: str = field(default="raw")
    outputs_per_step: int = field(default=3)
    stop_at_any: bool = field(default=True)
    batch_norm_position: str = field(default="after")
    clip_outputs: bool = field(default=False)
    lower_bound_decay: float = field(default=0.1)
    concat_speakers_with_encoder_output: bool = field(default=True)
    also_pass_condition_to_decoder: bool = field(default=False)
    architecture_type: str = field(default="duration_predictor")
    embedding_dim: int = field(default=512)
    use_finegrained_embeddings: bool = field(default=False)
    finegrained_embeddings_dim: int = field(default=10)
    number_of_tones: int = field(default=9)
    enc_use_cbhg: bool = field(default=False)
    enc_conv_num_layers: int = field(default=3)
    enc_conv_kernel_size: int = field(default=5)
    enc_conv_channels: int = field(default=512)
    encoder_lstm_units: int = field(default=256)
    attention: str = field(default="StepwiseMonotonic")
    smoothing: bool = field(default=False)
    attention_dim: int = field(default=128)
    attention_filters: int = field(default=32)
    attention_kernel: int = field(default=31)
    cumulative_weights: bool = field(default=False)
    use_attention_rnn: bool = field(default=False)
    stepwise_mode: str = field(default="parallel")
    use_score_bias: bool = field(default=True)
    score_bias_init: float = field(default=0.5)
    sigmoid_noise: float = field(default=0.3)
    normalize_attention_energy: bool = field(default=True)
    use_transition_agent: bool = field(default=False)
    prior_alpha: float = field(default=0.1)
    prior_beta: float = field(default=0.9)
    prior_filter_size: int = field(default=11)
    synthesis_constraint: bool = field(default=False)
    synthesis_constraint_type: str = field(default="window")
    attention_win_size: int = field(default=7)
    duration_predictor_layers: int = field(default=2)
    duration_predictor_lstm_units: int = field(default=256)
    upsampling_type: str = field(default="gaussian")
    positional_embedding_dim: int = field(default=32)
    duration_loss_coef: float = field(default=2.0)
    mask_duration_predictor: bool = field(default=False)
    mask_duration_predictor_values: bool = field(default=True)
    finetune_dp: bool = field(default=True)
    prenet_layers: List[int] = field(default_factory=[256, 256])
    decoder_lstm_units: List[int] = field(default_factory=[512, 512, 512])
    max_iters: int = field(default=2500)
    use_residual_rnn: bool = field(default=True)
    postnet_num_layers: int = field(default=5)
    postnet_kernel_size: List[int] = field(default_factory=[5, 5, 5, 5, 5])
    postnet_channels: int = field(default=512)
    cbhg_kernels: int = field(default=16)
    cbhg_conv_channels: int = field(default=128)
    cbhg_pool_size: int = field(default=2)
    cbhg_projection: int = field(default=128)
    cbhg_projections: List[int] = field(default_factory=[128, 128])
    cbhg_projection_kernel_size: int = field(default=3)
    cbhg_highwaynet_layers: int = field(default=4)
    cbhg_highway_units: int = field(default=128)
    cbhg_rnn_units: int = field(default=128)
    to_square_error: bool = field(default=False)
    loss_type: str = field(default="mixed")
    mask_encoder: bool = field(default=True)
    mask_decoder: bool = field(default=True)
    cross_entropy_pos_weight: int = field(default=1)
    masked_sigmoid_epsilon: float = field(default=0.0)
    use_adversarial_loss: bool = field(default=False)
    use_kl_loss: bool = field(default=False)
    use_speaker_embedding: bool = field(default=True)
    n_speakers: int = field(default=2)
    speakers_embedding_len: int = field(default=256)
    use_external_speaker_embeddings: bool = field(default=True)
    use_fixed_spk_embedding: bool = field(default=False)
    use_residual_encoder: bool = field(default=False)
    use_language_embedding: bool = field(default=False)
    n_languages: int = field(default=1)
    language_embedding_len: int = field(default=16)
    warmup_steps: int = field(default=1000)
    tacotron_random_seed: int = field(default=5339)
    tacotron_data_random_state: int = field(default=1234)
    tacotron_swap_with_cpu: bool = field(default=False)
    tacotron_batch_size: int = field(default=16)
    tacotron_synthesis_batch_size: int = field(default=1)
    tacotron_test_size: float = field(default=0.05)
    tacotron_test_batches: Optional[float] = field(default=None)
    store_train_data: bool = field(default=False)
    tacotron_decay_learning_rate: bool = field(default=True)
    tacotron_start_decay: int = field(default=4000)
    tacotron_decay_steps: int = field(default=50000)
    tacotron_decay_rate: float = field(default=0.5)
    tacotron_initial_learning_rate: float = field(default=0.001)
    tacotron_final_learning_rate: float = field(default=1e-05)
    tacotron_adam_beta1: float = field(default=0.9)
    tacotron_adam_beta2: float = field(default=0.999)
    tacotron_adam_epsilon: float = field(default=1e-06)
    tacotron_reg_weight: float = field(default=1e-06)
    tacotron_scale_regularization: bool = field(default=False)
    tacotron_zoneout_rate: float = field(default=0.1)
    tacotron_dropout_rate: float = field(default=0.5)
    tacotron_postnet_dropout_rate: float = field(default=0.1)
    tacotron_clip_gradients: bool = field(default=True)
    tacotron_natural_eval: bool = field(default=False)
    tacotron_teacher_forcing_mode: str = field(default="constant")
    tacotron_teacher_forcing_ratio: float = field(default=1.0)
    tacotron_teacher_forcing_init_ratio: float = field(default=1.0)
    tacotron_teacher_forcing_final_ratio: float = field(default=0.0)
    tacotron_teacher_forcing_start_decay: int = field(default=10000)
    tacotron_teacher_forcing_decay_steps: int = field(default=40000)
    tacotron_teacher_forcing_decay_alpha: Optional[float] = field(default=None)
    tacotron_fine_tuning: bool = field(default=False)
    uniform_language_distribution_in_batches: bool = field(default=False)
    tacotron_batch_group_size: int = field(default=64)
    feeder_type: str = field(default="simple")
    load_data_to_feeder_memory: bool = field(default=False)
    feeder_shuffling: bool = field(default=True)
